# Generated by Django 4.0.4 on 2022-06-22 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='Your first name(i.e; your name that people call you)', max_length=100)),
                ('last_name', models.CharField(max_length=100, verbose_name='Surname')),
                ('mail', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Snack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('P', 'P'), ('C', 'C'), ('J', 'J'), ('R', 'R'), ('PU', 'PU'), ('B', 'B'), ('FP', 'FP'), ('FR', 'FR'), ('ER', 'ER'), ('S', 'S')], help_text='The snack you want to order', max_length=2, verbose_name='Snack Type')),
                ('quantity', models.PositiveSmallIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placed_at', models.DateTimeField(auto_now_add=True)),
                ('payment_status', models.CharField(choices=[('P', 'Pending'), ('C', 'Completed'), ('F', 'Failed')], default='P', max_length=1)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='snacks.customer')),
                ('ordered_product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='snacks.snack')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='snacks.order')),
            ],
        ),
    ]
